[global]

[server]
runOnSave = true
port = 8501
address = "127.0.0.1"
enableCORS = false 
enableXsrfProtection = true 

[client]
toolbarMode = "auto"
#toolbarMode = "minimal"

[theme]
base="light"
primaryColor="#AA4AC4"
secondaryBackgroundColor="#ccf9ff"
textColor="#000000"
